# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# FYI: It might be incorrect.
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 0.4031710572
    has_acceleration_limits: true
    max_acceleration: 1.46607
  joint_2:
    has_velocity_limits: true
    max_velocity: 0.3921754829
    has_acceleration_limits: true
    max_acceleration: 1.46607
  joint_3:
    has_velocity_limits: true
    max_velocity: 0.725707903
    has_acceleration_limits: true
    max_acceleration: 2.44346
  joint_4:
    has_velocity_limits: true
    max_velocity: 0.7391469382
    has_acceleration_limits: true
    max_acceleration: 3.29867
  joint_5:
    has_velocity_limits: true
    max_velocity: 0.7391469382
    has_acceleration_limits: true
    max_acceleration: 3.29867
  joint_6:
    has_velocity_limits: true
    max_velocity: 1.1093312726
    has_acceleration_limits: true
    max_acceleration: 4.88692
  joint_gripper:
    has_velocity_limits: true
    max_velocity: 0.04
    has_acceleration_limits: false
    max_acceleration: 0
  joint_gripper_mimic:
    has_velocity_limits: true
    max_velocity: 0.04
    has_acceleration_limits: false
    max_acceleration: 0
